In [4]:
import pandas as pd

In [5]:
df = pd.read_pickle("feature_list")

In [13]:
df.sort_values(by = ["colorfulness"])

,valid_path,H,S,V,colorfulness,contrast,R,G,B,kelvin
47,../00_data/01_demo/photo-1487700160041-babef9c...,6.4210,6.7647,225.1142,8.620544,36.129470,233.859039,233.904060,233.856447,6445.342604
96,../00_data/01_demo/photo-1533090161767-e6ffed9...,65.6029,6.6372,195.5938,8.853710,17.148694,192.100884,192.007548,192.665301,6500.964226
29,../00_data/01_demo/ryoji-iwata-n31JPLu8_Pw-uns...,153.2492,16.2033,170.8709,9.843359,64.437387,99.604476,90.113825,98.057205,6476.336699
8,../00_data/01_demo/photo-1494438639946-1ebd1d2...,60.0738,18.8547,183.0539,10.084945,32.003404,166.030806,180.688849,168.888806,6525.039785
32,../00_data/01_demo/swabdesign-0HgPViWeIb8-unsp...,37.4229,30.5184,157.5004,10.201223,71.818444,229.034642,226.616373,222.578953,6067.364577
...,...,...,...,...,...,...,...,...,...,...
58,../00_data/01_demo/efe-kurnaz-RnCPiXixooY-unsp...,128.0655,156.3883,168.8944,92.653227,42.819550,83.471136,123.317130,152.239692,6440.395968
44,../00_data/01_demo/photo-1546548970-71785318a1...,67.7197,152.4266,194.0584,108.221563,57.000238,227.100231,196.309122,149.344718,2772.616369
50,../00_data/01_demo/photo-1483683804023-6ccdb62...,89.2167,187.3217,186.3669,109.314527,46.666245,6.087464,160.726742,181.843949,14676.250446
33,../00_data/01_demo/larisa-birta-kHVQFQFBufo-un...,93.8807,83.8398,219.0153,110.247544,67.424530,230.156786,229.080437,231.844983,3961.871035
75,../00_data/01_demo/charles-deluvio-Mv9hjnEUHR4...,49.9204,192.7565,173.6463,135.692034,62.935859,236.145130,180.264482,6.507937,3244.250416

In [15]:
df_prep = round(df, 2)

In [17]:
new_names = ['img_path', 'Hue', 'Saturation', 'Brightness', 'Colorfulness', 'Contrast', 'dom_Red', 'dom_G', 'dom_B',
       'temperature']

In [23]:
old_names = list(df_prep.columns)
old_names
rename = dict(zip(old_names, new_names))
rename

{'valid_path': 'img_path',
 'H': 'Hue',
 'S': 'Saturation',
 'V': 'Brightness',
 'colorfulness': 'Colorfulness',
 'contrast': 'Contrast',
 'R': 'dom_Red',
 'G': 'dom_G',
 'B': 'dom_B',
 'kelvin': 'temperature'}

In [36]:
df_prep = df_prep.rename(columns = rename)

In [38]:
df_prep.columns

Index(['img_path', 'Hue', 'Saturation', 'Brightness', 'Colorfulness',
       'Contrast', 'dom_Red', 'dom_G', 'dom_B', 'temperature'],
      dtype='object')

In [40]:
df_prep.loc[df_prep["img_path"] == "../00_data/01_demo/angello-pro-KxqEoimZPsM-unsplash.jpg"]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
10,../00_data/01_demo/angello-pro-KxqEoimZPsM-uns...,69.04,129.6,173.68,88.76,37.98,176.49,177.22,174.05,11857.02

In [41]:
img_1 = "../00_data/01_demo/vicko-mozara-m82uh_vamhg-unsplash.jpg"
img_2 = "../00_data/01_demo/photo-1483683804023-6ccdb62f86ef.jpeg"
img_3 = "../00_data/01_demo/photo-1507608616759-54f48f0af0ee.jpeg"
img_4 = "../00_data/01_demo/angello-pro-rnRz0dmn1SI-unsplash.jpg"

In [42]:
df_prep.loc[df_prep["img_path"] == img_1]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
55,../00_data/01_demo/vicko-mozara-m82uh_vamhg-un...,84.71,128.51,180.99,82.55,42.06,187.94,202.57,197.66,8843.76

In [43]:
df_prep.loc[df_prep["img_path"] == img_2]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
50,../00_data/01_demo/photo-1483683804023-6ccdb62...,89.22,187.32,186.37,109.31,46.67,6.09,160.73,181.84,14676.25

In [44]:
df_prep.loc[df_prep["img_path"] == img_3]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
90,../00_data/01_demo/photo-1507608616759-54f48f0...,92.39,192.06,168.94,89.07,37.01,2.12,136.83,157.41,16883.22

In [45]:
df_prep.loc[df_prep["img_path"] == img_4]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
82,../00_data/01_demo/angello-pro-rnRz0dmn1SI-uns...,51.82,105.49,152.08,66.02,36.58,168.73,169.85,149.74,7309.05

In [46]:


df_prep.loc[df_prep["img_path"] == "../00_data/01_demo/jason-leung-Xaanw0s0pMk-unsplash.jpg"]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
83,../00_data/01_demo/jason-leung-Xaanw0s0pMk-uns...,94.46,233.81,160.1,89.5,30.0,6.91,102.83,123.54,24471.16