In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle("feature_list")
pd.options.display.float_format = '{:20,.2f}'.format


df

,valid_path,H,S,V,colorfulness,contrast,R,G,B,kelvin
0,../00_data/01_demo/kelly-sikkema-4W1wo0U7Vuc-u...,101.31,121.18,74.58,30.31,0.14,35.48,22.97,21.34,"4,684.07"
1,../00_data/01_demo/pietro-jeng-0Sd2qqU5soQ-uns...,75.32,100.03,48.11,68.82,0.14,7.39,6.81,8.05,"1,905.71"
2,../00_data/01_demo/photo-1505069446780-4ef442b...,56.00,35.67,123.37,15.94,0.22,51.87,50.31,44.44,"6,290.82"
3,../00_data/01_demo/simone-mascellari-7QK_VsynT...,65.07,62.93,92.32,16.80,0.28,21.30,26.19,29.16,"6,026.17"
4,../00_data/01_demo/dusan-smetana-ZXuDkw7Be7E-u...,19.24,97.01,162.13,33.08,0.17,178.55,153.83,115.32,"4,150.66"
...,...,...,...,...,...,...,...,...,...,...
96,../00_data/01_demo/maksym-ivashchenko-7P9cPzWK...,66.36,102.05,61.07,19.85,0.13,20.42,18.07,11.36,"6,952.03"
97,../00_data/01_demo/photo-1533090161767-e6ffed9...,65.60,6.64,195.59,8.85,0.07,190.10,190.02,190.04,"6,500.96"
98,../00_data/01_demo/photo-1533038590840-1cde6e6...,102.21,18.06,227.12,20.94,0.20,245.02,245.27,246.97,"6,335.77"
99,../00_data/01_demo/smit-patel-dGMcpbzcq1I-unsp...,45.52,40.68,71.70,18.54,0.20,35.34,39.37,34.29,"6,039.82"
100,../00_data/01_demo/photo-1524293568345-75d62c3...,105.84,203.76,212.87,136.33,0.14,11.29,197.73,228.71,"14,617.52"

In [3]:
df.sort_values(by = ["colorfulness"])

,valid_path,H,S,V,colorfulness,contrast,R,G,B,kelvin
49,../00_data/01_demo/photo-1487700160041-babef9c...,6.42,6.76,225.11,8.62,0.14,233.85,233.89,233.84,"6,445.34"
97,../00_data/01_demo/photo-1533090161767-e6ffed9...,65.60,6.64,195.59,8.85,0.07,190.10,190.02,190.04,"6,500.96"
31,../00_data/01_demo/ryoji-iwata-n31JPLu8_Pw-uns...,153.25,16.20,170.87,9.84,0.25,99.60,90.11,98.06,"6,476.34"
8,../00_data/01_demo/photo-1494438639946-1ebd1d2...,60.07,18.85,183.05,10.08,0.13,166.03,180.69,168.89,"6,525.04"
34,../00_data/01_demo/swabdesign-0HgPViWeIb8-unsp...,37.42,30.52,157.50,10.20,0.28,229.03,226.61,222.58,"6,067.36"
...,...,...,...,...,...,...,...,...,...,...
46,../00_data/01_demo/photo-1546548970-71785318a1...,67.72,152.43,194.06,108.22,0.22,227.00,195.89,149.46,"2,772.62"
52,../00_data/01_demo/photo-1483683804023-6ccdb62...,89.22,187.32,186.37,109.31,0.18,5.97,160.59,181.75,"14,676.25"
35,../00_data/01_demo/larisa-birta-kHVQFQFBufo-un...,93.88,83.84,219.02,110.25,0.26,230.21,229.14,231.92,"3,961.87"
77,../00_data/01_demo/charles-deluvio-Mv9hjnEUHR4...,49.92,192.76,173.65,135.69,0.25,236.15,180.26,6.51,"3,244.25"
100,../00_data/01_demo/photo-1524293568345-75d62c3...,105.84,203.76,212.87,136.33,0.14,11.29,197.73,228.71,"14,617.52"

In [4]:
df_prep = round(df, 2)

In [5]:
new_names = ['img_path', 'Hue', 'Saturation', 'Brightness', 'Colorfulness', 'Contrast', 'dom_Red', 'dom_G', 'dom_B',
       'temperature']

In [6]:
old_names = list(df_prep.columns)
old_names
rename = dict(zip(old_names, new_names))
rename

{'valid_path': 'img_path',
 'H': 'Hue',
 'S': 'Saturation',
 'V': 'Brightness',
 'colorfulness': 'Colorfulness',
 'contrast': 'Contrast',
 'R': 'dom_Red',
 'G': 'dom_G',
 'B': 'dom_B',
 'kelvin': 'temperature'}

In [17]:
df_prep = df_prep.rename(columns = rename)
df_prep

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
0,../00_data/01_demo/kelly-sikkema-4W1wo0U7Vuc-u...,101.31,121.18,74.58,30.31,0.14,35.48,22.97,21.34,"4,684.07"
1,../00_data/01_demo/pietro-jeng-0Sd2qqU5soQ-uns...,75.32,100.03,48.11,68.82,0.14,7.39,6.81,8.05,"1,905.71"
2,../00_data/01_demo/photo-1505069446780-4ef442b...,56.00,35.67,123.37,15.94,0.22,51.87,50.31,44.44,"6,290.82"
3,../00_data/01_demo/simone-mascellari-7QK_VsynT...,65.07,62.93,92.32,16.80,0.28,21.30,26.19,29.16,"6,026.17"
4,../00_data/01_demo/dusan-smetana-ZXuDkw7Be7E-u...,19.24,97.01,162.13,33.08,0.17,178.55,153.83,115.32,"4,150.66"
...,...,...,...,...,...,...,...,...,...,...
96,../00_data/01_demo/maksym-ivashchenko-7P9cPzWK...,66.36,102.05,61.07,19.85,0.13,20.42,18.07,11.36,"6,952.03"
97,../00_data/01_demo/photo-1533090161767-e6ffed9...,65.60,6.64,195.59,8.85,0.07,190.10,190.02,190.04,"6,500.96"
98,../00_data/01_demo/photo-1533038590840-1cde6e6...,102.21,18.06,227.12,20.94,0.20,245.02,245.27,246.97,"6,335.77"
99,../00_data/01_demo/smit-patel-dGMcpbzcq1I-unsp...,45.52,40.68,71.70,18.54,0.20,35.34,39.37,34.29,"6,039.82"
100,../00_data/01_demo/photo-1524293568345-75d62c3...,105.84,203.76,212.87,136.33,0.14,11.29,197.73,228.71,"14,617.52"

In [8]:
df_prep.columns

Index(['img_path', 'Hue', 'Saturation', 'Brightness', 'Colorfulness',
       'Contrast', 'dom_Red', 'dom_G', 'dom_B', 'temperature'],
      dtype='object')

In [18]:
df_prep.loc[df_prep["img_path"] == "../00_data/01_demo/angello-pro-KxqEoimZPsM-unsplash.jpg"]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
10,../00_data/01_demo/angello-pro-KxqEoimZPsM-uns...,69.04,129.60,173.68,88.76,0.15,176.66,177.27,174.06,"11,857.02"

In [10]:
img_1 = "../00_data/01_demo/vicko-mozara-m82uh_vamhg-unsplash.jpg"
img_2 = "../00_data/01_demo/photo-1483683804023-6ccdb62f86ef.jpeg"
img_3 = "../00_data/01_demo/photo-1507608616759-54f48f0af0ee.jpeg"
img_4 = "../00_data/01_demo/angello-pro-rnRz0dmn1SI-unsplash.jpg"

In [25]:
df_prep.loc[df_prep["img_path"] == (img_1)]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
57,../00_data/01_demo/vicko-mozara-m82uh_vamhg-un...,84.71,128.51,180.99,82.55,0.16,188.12,202.67,197.78,"8,843.76"

In [12]:
df_prep.loc[df_prep["img_path"] == img_2]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
52,../00_data/01_demo/photo-1483683804023-6ccdb62...,89.22,187.32,186.37,109.31,0.18,5.97,160.59,181.75,"14,676.25"

In [13]:
df_prep.loc[df_prep["img_path"] == img_3]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
91,../00_data/01_demo/photo-1507608616759-54f48f0...,92.39,192.06,168.94,89.07,0.15,2.10,136.81,157.38,"16,883.22"

In [14]:
df_prep.loc[df_prep["img_path"] == img_4]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
83,../00_data/01_demo/angello-pro-rnRz0dmn1SI-uns...,51.82,105.49,152.08,66.02,0.14,168.73,169.85,149.74,"7,309.05"

In [15]:


df_prep.loc[df_prep["img_path"] == "../00_data/01_demo/jason-leung-Xaanw0s0pMk-unsplash.jpg"]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
84,../00_data/01_demo/jason-leung-Xaanw0s0pMk-uns...,94.46,233.81,160.10,89.50,0.12,6.91,102.83,123.54,"24,471.16"

In [16]:
df_prep.loc[df_prep["img_path"] == "../00_data/01_demo/photo-1524293568345-75d62c3664f7.jpeg"]

,img_path,Hue,Saturation,Brightness,Colorfulness,Contrast,dom_Red,dom_G,dom_B,temperature
100,../00_data/01_demo/photo-1524293568345-75d62c3...,105.84,203.76,212.87,136.33,0.14,11.29,197.73,228.71,"14,617.52"